name = "Pyth rebased prices oracle"
type = "PYTH"
url =" https://github.com/vegaprotocol/pyth-rebase-contract"
description_markdown = """
# Pyth rebased prices oracle

A simple contract providing prices from the pyth on chain oracles quoted in USDT
"""

[oracle]
source_chain = "gnosis"
source_chain_id = "100"
type = "eth_address"
eth_address= "0x719abd606155442c21b7d561426d42bd0e40a776"
status = "GOOD"
status_reason = ""
first_verified = 2023-05-22T00:00:00Z
last_verified = 2023-05-22T00:00:00Z

[[proofs]]
type = "web"
format = "url"
url = "https://gnosisscan.io/address/0x719abd606155442c21b7d561426d42bd0e40a776#code"
available = true
